package com.platformer;

/**
 * Contains the data for the levels of the game.
 *
 * @author Samuel Zhang
 */
public interface GameLevels {

    // constants for each page
    int INSTRUCTIONS = 10;
    int MAIN_MENU = 11;
    int LEVEL_SELECTION = 12;
    int OPTIONS_MENU = 13;
    int LEADERBOARDS = 14;

    /**
     * 2D array of all the pages in the game.
     */
    String[][] PAGES = {
            {}, // empty for index 0
            { // level 1
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww            ggggg                        ww",
                    "wwf                         ggggg          ww",
                    "wwww                ggggg          wwww    ww",
                    "wwww  ggggg                        wwww   cww",
                    "wwwwlllllllllllllllllllllllllllllllwwwwwwppww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww  ww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww  ww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww           ww",
                    "wwwwwwwwwwwwwwwwwwwwwwww                   ww",
                    "wwwwwwwwwwwwww                           wwww",
                    "wwwwww                                   wwww",
                    "ww                                 wwwww wwww",
                    "ww                          wwwww  wwwww wwww",
                    "ww                   wwwww  wwwww  wwwww wwww",
                    "ww            wwwww  wwwww  wwwww  wwwww wwww",
                    "wws    wwwwwllwwwwwllwwwwwllwwwwwllwwwwwlwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            },
            { // level 2
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "ww                                         ww",
                    "ww                         wwww            ww",
                    "ww                    wwww wwww            ww",
                    "ww              gggg  wwww wwww  wwww     fww",
                    "ww                    wwwwlwwwwllwwwwlllwwwww",
                    "ww      gggg          wwwwwwwwwwwwwwwwwwwwwww",
                    "ww                       wwwwwwwwwwwwwwwwwwww",
                    "wwgg                            wwwwwwwwwwwww",
                    "ww                                     wwwwww",
                    "wwc                                        ww",
                    "wwwwwwwllllwwwwwllllwwwww                  ww",
                    "wwwwwwwwwwwwwwwwwwwwwwwww                  ww",
                    "wwwwwwwwwwwwwwwwwwwww        ggggg         ww",
                    "wwwwwwwwwwwwww                            cww",
                    "wwwwwww                               gggggww",
                    "ww                                         ww",
                    "ww                           ggggg         ww",
                    "ww                                         ww",
                    "ww                  ggggg                  ww",
                    "ww                                         ww",
                    "ww        wwwwww                           ww",
                    "wws       wwwwwwlllllllllllllllllllllllllllww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            },
            { // level 3
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwwws                  wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwpppwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwlllll    llllllllllwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwggggg    ggggggggggwwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwllllllllll    lllllwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwgggggggggg    gggggwwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwllllll    lllllllllwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwgggggg    gggggggggwwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwllllllllll    lllllwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwgggggggggg    gggggwwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwlllllllllllll    llwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwggggggggggggg    ggwwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwc                  wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwpppwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwlllllllllllll    llwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwggggggggggggg    ggwwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwlllllllll    llllllwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwggggggggg    ggggggwwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwllll    lllllllllllwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwgggg    gggggggggggwwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwllllllll    lllllllwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwgggggggg    gggggggwwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwf                  wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwllllllllllwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            },
            { // level 4
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "ww                                         ww",
                    "ww          gggg                           ww",
                    "wwf              gggg        gggg  gggg    ww",
                    "wwgggggggg             gggg              ppww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                       ggww",
                    "ww                      gggg     gggg      ww",
                    "wwc     gggg                               ww",
                    "wwpp             gggg                      ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "wwgg                      gggg             ww",
                    "ww      gggg                      gggg     ww",
                    "ww              gggg                       ww",
                    "ww                                       ggww",
                    "ww                                         ww",
                    "ww                               gggg      ww",
                    "ww              gggg     gggg              ww",
                    "wws                                        ww",
                    "wwwwww   gggg                              ww",
                    "wwwwwwlllllllllllllllllllllllllllllllllllllww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            },
            { // level 5
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "ww                                                                                      ww",
                    "ww           pp                                                                         ww",
                    "ww                     pp                   pp                                         fww",
                    "ww  pp                             pp                       pp                      ggggww",
                    "ww                 pp                             pp                            pp      ww",
                    "ww          pp                                                           pp             ww",
                    "ww                       pp         pp                 pp         pp                    ww",
                    "ww                                                                                   pp ww",
                    "ww                pp                           pp                                       ww",
                    "ww     pp                       pp                          pp               pp         ww",
                    "ww                   pp                                                                 ww",
                    "ww pp                                   pp                        pp                    ww",
                    "ww            pp                                   pp                             pp    ww",
                    "ww                      pp                  pp                            pp            ww",
                    "ww   pp                            pp                        pp                         ww",
                    "ww                 pp       pp                         pp                      pp       ww",
                    "ww         pp                                  pp                  pp                 ppww",
                    "ww                    pp             pp                                  pp             ww",
                    "wws                                       pp                                            ww",
                    "wwwwwwwww     pp               pp                            pp                   pp    ww",
                    "wwwwwwwww            pp                            pp                  pp               ww",
                    "wwwwwwwwwlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllww",
            },
            { // level 6
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "wws                                        ww",
                    "wwwwwwwwwwwwwwwwwwwwwpppwwwwwwwwwwwwwwwwwwwww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                              llllllll   ww",
                    "ww          llllllll            gggggggg   ww",
                    "ww          gggggggg                       ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "wwllllllll                                 ww",
                    "wwgggggggg             llllllll            ww",
                    "ww                     gggggggg            ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww     llllllll                            ww",
                    "ww     gggggggg      llllllll              ww",
                    "ww                   gggggggg              ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                               llllllll  ww",
                    "ww           llllllll            gggggggg  ww",
                    "ww           gggggggg                      ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww       llllllll                          ww",
                    "ww       gggggggg                          ww",
                    "ww                          llllllll       ww",
                    "ww                          gggggggg       ww",
                    "ww                                         ww",
                    "ww  llllllll                               ww",
                    "ww  gggggggg     llllllll                  ww",
                    "ww               gggggggg      llllllll    ww",
                    "ww                             gggggggg    ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                         llllllll        ww",
                    "ww        llllllll         gggggggg        ww",
                    "ww        gggggggg                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                llllllll                 ww",
                    "ww                gggggggg                 ww",
                    "ww                              llllllll   ww",
                    "ww                              gggggggg   ww",
                    "ww    llllllll                             ww",
                    "ww    gggggggg      llllllll               ww",
                    "ww                  gggggggg               ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                               llllllll  ww",
                    "ww             llllllll          gggggggg  ww",
                    "ww             gggggggg                    ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww  llllllll                               ww",
                    "ww  gggggggg            llllllll           ww",
                    "ww                      gggggggg           ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "wwllllllll        llllllll         llllllllww",
                    "wwgggggggg        gggggggg         ggggggggww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "wwf                                        ww",
                    "wwwwwwwwwwwwwwlllllllllllllllllllllllllllllww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            },
            { // level 7
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwwws                  wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwggggggggpppggggggggwwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww   llll            wwwwwwwwwwwww",
                    "wwwwwwwwwwwww   gggg            wwwwwwwwwwwww",
                    "wwwwwwwwwwwww            llll   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww            gggg   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww       llll        wwwwwwwwwwwww",
                    "wwwwwwwwwwwww       gggg        wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww             llll  wwwwwwwwwwwww",
                    "wwwwwwwwwwwww llll        gggg  wwwwwwwwwwwww",
                    "wwwwwwwwwwwww gggg              wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww       llll        wwwwwwwwwwwww",
                    "wwwwwwwwwwwww       gggg        wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww            llll   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww            gggg   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww    llll           wwwwwwwwwwwww",
                    "wwwwwwwwwwwww    gggg           wwwwwwwwwwwww",
                    "wwwwwwwwwwwww               llllwwwwwwwwwwwww",
                    "wwwwwwwwwwwww               ggggwwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww       llll        wwwwwwwwwwwww",
                    "wwwwwwwwwwwww       gggg        wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwllll               wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwgggg               wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww    lllllllllllllllwwwwwwwwwwwww",
                    "wwwwwwwwwwwww    gggggggggggggggwwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww           llll    wwwwwwwwwwwww",
                    "wwwwwwwwwwwww           gggg    wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwllll               wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwgggg               wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww         llll      wwwwwwwwwwwww",
                    "wwwwwwwwwwwww         gggg      wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww   llll            wwwwwwwwwwwww",
                    "wwwwwwwwwwwww   gggg       llll wwwwwwwwwwwww",
                    "wwwwwwwwwwwww              gggg wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww        llll       wwwwwwwwwwwww",
                    "wwwwwwwwwwwww        gggg       wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwllll               wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwgggg               wwwwwwwwwwwww",
                    "wwwwwwwwwwwww               llllwwwwwwwwwwwww",
                    "wwwwwwwwwwwww               ggggwwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww  llll             wwwwwwwwwwwww",
                    "wwwwwwwwwwwww  gggg             wwwwwwwwwwwww",
                    "wwwwwwwwwwwww          llll     wwwwwwwwwwwww",
                    "wwwwwwwwwwwww          gggg     wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww        llll       wwwwwwwwwwwww",
                    "wwwwwwwwwwwww        gggg       wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwww                   wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwll   llllllll   lllwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwww   wwwwwwww   wwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwww        ww         wwwwwwwwwwwww",
                    "wwwwwwwwwwwww        ww         wwwwwwwwwwwww",
                    "wwwwwwwwwwwww       cwwc        wwwwwwwwwwwww",
                    "wwwwwwwwwwwww wwwwwwwwwwwwwwwww wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwpgwwggggggggggggggpwwwwwwwwwwwww",
                    "wwwwwwwwwwwww  ww               wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwl ww               wwwwwwwwwwwww",
                    "wwwwwwwwwwwww  wwppwwwwww       wwwwwwwwwwwww",
                    "wwwwwwwwwwwww  ww    wwwwlllwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwww lww    wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwww  wwll  wwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwww  wwgg  www        wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwl ww    www        wwwwwwwwwwwww",
                    "wwwwwwwwwwwww  ww    www        wwwwwwwwwwwww",
                    "wwwwwwwwwwwww  ww  llwww        wwwwwwwwwwwww",
                    "wwwwwwwwwwwwwflww  ggggg       fwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwww            wwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwlllllwwwwwwwwwwwwwwww",
            },
            { // level 8
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "ww                                                                                                ww",
                    "ww                                                                                                ww",
                    "wws                                              wwwllwwwllwwwllwwwllwwwllwwwllwwwllwwwllwwwllw  cww",
                    "wwwwwwwlllwwwlllwwwlllwwwlllwwwlllwwwlllwwwlllwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwppwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww         www                       ww    ww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww    www  www      www              ww  llww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww    www gwww  wwllwww ggggggggggg  ww  ggww",
                    "ww                                                           www  www  ggggwww              ww    ww",
                    "ww         gg gg                                             www  www      www              ww    ww",
                    "ww               g                g                          www gwwwllww  www     gg   gg  wwll  ww",
                    "ww                  g                               g       cwww  ggggggg  www              gggg  ww",
                    "wwc                     g             g        g         wwwwwww           www                    ww",
                    "wwwwppww                     g              g            wwwwwwwlwwwllwwwllwwwgg                  ww",
                    "ww    wwlllllllllllllllllllllllllllllllllllllllllllllllllwwwwwwwwwwwwwwwwwwwwwllllllwwllllwwwwwwllww",
                    "ww    wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "ww  llww        wwww    wwww                                                                      ww",
                    "ww  gggg  wwwwppwwww    wwww                                                                      ww",
                    "ww        wwww lwwww    wwww                                                                      ww",
                    "ww     gg wwww gwwww    wwww                                                                      ww",
                    "ww        wwww                            gg    gg                gg                              ww",
                    "wwlllwwlllwwww    gg    wwwwc       gg                      gg                 gg                fww",
                    "wwwwwwwwwwwwww          wwwwwww                       gg                  gg           gg     wwwwww",
                    "wwwwwwwwwwwwwwllwwllllllwwwwwwwlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllwwwwww",
            },
            { // level 9
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwlllllwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwww     wwwww    wwwwwwwwwwwwwwwwwww",
                    "wwgggggggwww     wwwww    wwwwwgggggwwwwwwwww",
                    "ww    ww ggw     wwggg    wwwww     wwwwwwwww",
                    "ww wllwwlwcg     ggcww    wwwww     wwwwwwwww",
                    "ww wwwwwwwwwlllllwwwww      c          c   ww",
                    "wwpgwwwwwwww     wwwwwllllwwwwwlllllwwwwww ww",
                    "ww  wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww ww",
                    "wwl wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwl   ww",
                    "ww  ww    l                         wwwwww ww",
                    "ww  ww                              wwwwww ww",
                    "ww lww    l     ll     ll     ll   fwwwl   ww",
                    "ww  ww    w     wwc               wwwwwwww ww",
                    "ww  c     w     wwwww  ww     ww  wwwwwwww ww",
                    "wwlwwwwwllwllwwwwwwwwllwwlllllwwllww   c   ww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww wwwwwlww",
                    "ww          wwwwwwwwwwwwwwwwwwwwwwww wwwwwwww",
                    "ww          wwwww     wwwwwwwwpppppw       ww",
                    "ww          wwwww     wwwwwwww     wlwwwww ww",
                    "wws         wwwww          www     wwwwwww ww",
                    "wwwwww        c       wwwc            c    ww",
                    "wwwwwwllllllwwwwwlllllwwwwwwwwlllllwwwwwwwlww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            },
            { // instructions
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww           s           w                 ww",
                    "ww           c           l                 ww",
                    "ww                                         ww",
                    "ww           f           g                 ww",
                    "ww                       p                 ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                      G  ww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            },
            { // main menu
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww   www w w ww  www     www w w w w www   ww",
                    "ww   w   w w w w w        w  w w www w w   ww",
                    "ww   w   w w ww  ww       w  w w www www   ww",
                    "ww   w   w w w w w        w  w w w w w     ww",
                    "ww   www www ww  www     ww  www w w w     ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww           S                 O           ww",
                    "ww        ggggggg           ggggggg        ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                 ggggggg                 ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            },
            { // level selection
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                    9                    ww",
                    "ww                  ggggg                  ww",
                    "ww           7                 8           ww",
                    "ww         ggggg             ggggg         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww    ggg                           ggg    ww",
                    "ww                                         ww",
                    "ww           4        5        6           ww",
                    "ww         ggggg    ggggg    ggggg         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww    ggg                           ggg    ww",
                    "ww                                         ww",
                    "ww           1        2        3        B  ww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            },
            { // options
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwww                                     wwww",
                    "wwww                                     wwww",
                    "wwww                                     wwww",
                    "wwww                                     wwww",
                    "wwww                                     wwww",
                    "wwww                                     wwww",
                    "wwww                                     wwww",
                    "wwww        L                   D        wwww",
                    "wwww     ggggggg             ggggggg     wwww",
                    "wwww                                     wwww",
                    "wwww                                     wwww",
                    "wwww              ggggggggg              wwww",
                    "wwww                                     wwww",
                    "wwww  B                              I   wwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            },
            { // level stats
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww                                         ww",
                    "ww  B                                      ww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
                    "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
            },
    };

}